name: Android CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 修复：使用 Android 推荐的 JDK 17（而非 21，减少兼容性问题）
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease -P "version=${{ github.ref_name }}"  # 参数加引号更安全

      # 新增步骤：定位构建生成的 APK 路径（根据实际输出目录调整）
      - name: Locate APKs
        id: locate_apks
        run: |
          # 假设构建后生成的 Normal 和 Compatible 版本 APK 路径如下（根据实际项目结构调整）
          normal_apk=$(find app/build/outputs/apk/normal/release -name "*.apk" | head -n 1)
          compatible_apk=$(find app/build/outputs/apk/compatible/release -name "*.apk" | head -n 1)
          # 输出路径到变量，供后续步骤使用
          echo "normal_apk=$normal_apk" >> $GITHUB_OUTPUT
          echo "compatible_apk=$compatible_apk" >> $GITHUB_OUTPUT

      # 新增步骤：生成校验和文件（SHA256）
      - name: Generate APK Checksums
        id: generate_checksums
        run: |
          # 获取短 commit SHA（前7位）并设置为环境变量
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          # 生成 Normal 版本校验和
          sha256sum ${{ steps.locate_apks.outputs.normal_apk }} > "CHECKSUMS-Sesame-Normal-${{ github.ref_name }}.${{ env.SHORT_SHA }}.sha256"
          # 生成 Compatible 版本校验和
          sha256sum ${{ steps.locate_apks.outputs.compatible_apk }} > "CHECKSUMS-Sesame-Compatible-${{ github.ref_name }}.${{ env.SHORT_SHA }}.sha256"

      # 修复：上传步骤引用正确的变量
      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.release.tag_name }}  # 直接使用 Release 标签名作为名称
          # 上传文件：使用定位步骤获取的 APK 路径和生成的校验和文件
          files: |
            ${{ steps.locate_apks.outputs.compatible_apk }}
            ${{ steps.locate_apks.outputs.normal_apk }}
            CHECKSUMS-Sesame-Normal-${{ github.ref_name }}.${{ env.SHORT_SHA }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.ref_name }}.${{ env.SHORT_SHA }}.sha256
          tag_name: ${{ github.ref_name }}  # 直接使用 Release 标签（与触发事件一致）
          draft: false
          append_body: true
          generate_release_notes: true
          body: |
            ## ✨What's Changed

            ${{ github.event.head_commit.message || github.event.pull_request.title || '无详细信息' }}
            > ## 下载说明
              * Normal 为正常版本,适用于`Android 8.0`及以上的系统
              * Compatible 为兼容版本,适用于`Android 7.0`不再向下兼容 参考minSDK24后续不再兼容`
            > 倒卖必死全家
